-- Drop all tables if they exist
DROP TABLE IF EXISTS public."TreeIncidentImages" CASCADE;
DROP TABLE IF EXISTS public."WorkUsers" CASCADE;
DROP TABLE IF EXISTS public."WorkProgresses" CASCADE;
DROP TABLE IF EXISTS public."WorkDetails" CASCADE;
DROP TABLE IF EXISTS public."TreeLocationHistories" CASCADE;
DROP TABLE IF EXISTS public."TreeIncidents" CASCADE;
DROP TABLE IF EXISTS public."Locations" CASCADE;
DROP TABLE IF EXISTS public."AspNetUserTokens" CASCADE;
DROP TABLE IF EXISTS public."AspNetUserRoles" CASCADE;
DROP TABLE IF EXISTS public."AspNetUserLogins" CASCADE;
DROP TABLE IF EXISTS public."AspNetUserClaims" CASCADE;
DROP TABLE IF EXISTS public."Works" CASCADE;
DROP TABLE IF EXISTS public."Trees" CASCADE;
DROP TABLE IF EXISTS public."TodoItems" CASCADE;
DROP TABLE IF EXISTS public."Streets" CASCADE;
DROP TABLE IF EXISTS public."Plans" CASCADE;
DROP TABLE IF EXISTS public."AspNetUsers" CASCADE;
DROP TABLE IF EXISTS public."AspNetRoleClaims" CASCADE;
DROP TABLE IF EXISTS public."WorkTypes" CASCADE;
DROP TABLE IF EXISTS public."Wards" CASCADE;
DROP TABLE IF EXISTS public."TreeTypes" CASCADE;
DROP TABLE IF EXISTS public."TodoLists" CASCADE;
DROP TABLE IF EXISTS public."AspNetRoles" CASCADE;

-- Now create all tables

-- public."AspNetRoles" definition

CREATE TABLE public."AspNetRoles" (
	"Id" text NOT NULL,
	"Name" varchar(256) NULL,
	"NormalizedName" varchar(256) NULL,
	"ConcurrencyStamp" text NULL,
	CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX "RoleNameIndex" ON public."AspNetRoles" USING btree ("NormalizedName");

-- public."TodoLists" definition

CREATE TABLE public."TodoLists" (
	"Id" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"Title" varchar(200) NOT NULL,
	"Colour_Code" text NOT NULL,
	"Created" timestamptz NOT NULL,
	"CreatedBy" text NULL,
	"LastModified" timestamptz NOT NULL,
	"LastModifiedBy" text NULL,
	CONSTRAINT "PK_TodoLists" PRIMARY KEY ("Id")
);

-- public."TreeTypes" definition

CREATE TABLE public."TreeTypes" (
	"Id" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"Name" text NULL,
	"Group" text NULL,
	"Created" timestamptz NOT NULL,
	"CreatedBy" text NULL,
	"LastModified" timestamptz NOT NULL,
	"LastModifiedBy" text NULL,
	CONSTRAINT "PK_TreeTypes" PRIMARY KEY ("Id")
);

-- public."Wards" definition

CREATE TABLE public."Wards" (
	"Id" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"Name" varchar(200) NOT NULL,
	"Created" timestamptz NOT NULL,
	"CreatedBy" text NULL,
	"LastModified" timestamptz NOT NULL,
	"LastModifiedBy" text NULL,
	CONSTRAINT "PK_Wards" PRIMARY KEY ("Id")
);

-- public."WorkTypes" definition

CREATE TABLE public."WorkTypes" (
	"Id" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"Name" text NULL,
	"Created" timestamptz NOT NULL,
	"CreatedBy" text NULL,
	"LastModified" timestamptz NOT NULL,
	"LastModifiedBy" text NULL,
	CONSTRAINT "PK_WorkTypes" PRIMARY KEY ("Id")
);

-- public."AspNetRoleClaims" definition

CREATE TABLE public."AspNetRoleClaims" (
	"Id" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"RoleId" text NOT NULL,
	"ClaimType" text NULL,
	"ClaimValue" text NULL,
	CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
	CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON public."AspNetRoleClaims" USING btree ("RoleId");

-- public."AspNetUsers" definition

CREATE TABLE public."AspNetUsers" (
	"Id" text NOT NULL,
	"WardId" int4 NULL,
	"FullName" text NULL,
	"DateOfBirth" timestamptz NULL,
	"Status" int4 NOT NULL,
	"UserName" varchar(256) NULL,
	"NormalizedUserName" varchar(256) NULL,
	"Email" varchar(256) NULL,
	"NormalizedEmail" varchar(256) NULL,
	"EmailConfirmed" bool NOT NULL,
	"PasswordHash" text NULL,
	"SecurityStamp" text NULL,
	"ConcurrencyStamp" text NULL,
	"PhoneNumber" text NULL,
	"PhoneNumberConfirmed" bool NOT NULL,
	"TwoFactorEnabled" bool NOT NULL,
	"LockoutEnd" timestamptz NULL,
	"LockoutEnabled" bool NOT NULL,
	"AccessFailedCount" int4 NOT NULL,
	CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id"),
	CONSTRAINT "FK_AspNetUsers_Wards_WardId" FOREIGN KEY ("WardId") REFERENCES public."Wards"("Id") ON DELETE SET NULL
);

CREATE INDEX "EmailIndex" ON public."AspNetUsers" USING btree ("NormalizedEmail");
CREATE INDEX "IX_AspNetUsers_WardId" ON public."AspNetUsers" USING btree ("WardId");
CREATE UNIQUE INDEX "UserNameIndex" ON public."AspNetUsers" USING btree ("NormalizedUserName");

-- public."Plans" definition

CREATE TABLE public."Plans" (
	"Id" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"Name" text NULL,
	"CreatorId" text NOT NULL,
	"ApproverId" text NULL,
	"CreatedDate" timestamptz NULL,
	"StartDate" timestamptz NULL,
	"EndDate" timestamptz NULL,
	"Status" text NULL,
	"Created" timestamptz NOT NULL,
	"CreatedBy" text NULL,
	"LastModified" timestamptz NOT NULL,
	"LastModifiedBy" text NULL,
	CONSTRAINT "PK_Plans" PRIMARY KEY ("Id"),
	CONSTRAINT "FK_Plans_AspNetUsers_ApproverId" FOREIGN KEY ("ApproverId") REFERENCES public."AspNetUsers"("Id") ON DELETE RESTRICT,
	CONSTRAINT "FK_Plans_AspNetUsers_CreatorId" FOREIGN KEY ("CreatorId") REFERENCES public."AspNetUsers"("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_Plans_ApproverId" ON public."Plans" USING btree ("ApproverId");
CREATE INDEX "IX_Plans_CreatorId" ON public."Plans" USING btree ("CreatorId");

-- public."Streets" definition

CREATE TABLE public."Streets" (
	"Id" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"WardId" int4 NOT NULL,
	"Name" text NULL,
	"Created" timestamptz NOT NULL,
	"CreatedBy" text NULL,
	"LastModified" timestamptz NOT NULL,
	"LastModifiedBy" text NULL,
	CONSTRAINT "PK_Streets" PRIMARY KEY ("Id"),
	CONSTRAINT "FK_Streets_Wards_WardId" FOREIGN KEY ("WardId") REFERENCES public."Wards"("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Streets_WardId" ON public."Streets" USING btree ("WardId");

-- public."TodoItems" definition

CREATE TABLE public."TodoItems" (
	"Id" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"ListId" int4 NOT NULL,
	"Title" varchar(200) NOT NULL,
	"Note" text NULL,
	"Priority" int4 NOT NULL,
	"Reminder" timestamptz NULL,
	"Done" bool NOT NULL,
	"Created" timestamptz NOT NULL,
	"CreatedBy" text NULL,
	"LastModified" timestamptz NOT NULL,
	"LastModifiedBy" text NULL,
	CONSTRAINT "PK_TodoItems" PRIMARY KEY ("Id"),
	CONSTRAINT "FK_TodoItems_TodoLists_ListId" FOREIGN KEY ("ListId") REFERENCES public."TodoLists"("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_TodoItems_ListId" ON public."TodoItems" USING btree ("ListId");

-- public."Trees" definition

CREATE TABLE public."Trees" (
	"Id" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"TreeTypeId" int4 NOT NULL,
	"Name" text NULL,
	"Condition" text NULL,
	"Height" numeric NULL,
	"TrunkDiameter" numeric NULL,
	"RecordedDate" timestamptz NULL,
	"Created" timestamptz NOT NULL,
	"CreatedBy" text NULL,
	"LastModified" timestamptz NOT NULL,
	"LastModifiedBy" text NULL,
	CONSTRAINT "PK_Trees" PRIMARY KEY ("Id"),
	CONSTRAINT "FK_Trees_TreeTypes_TreeTypeId" FOREIGN KEY ("TreeTypeId") REFERENCES public."TreeTypes"("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Trees_TreeTypeId" ON public."Trees" USING btree ("TreeTypeId");

-- public."Works" definition

CREATE TABLE public."Works" (
	"Id" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"WorkTypeId" int4 NOT NULL,
	"CreatorId" text NOT NULL,
	"PlanId" int4 NOT NULL,
	"CreatedDate" timestamptz NULL,
	"StartDate" timestamptz NULL,
	"EndDate" timestamptz NULL,
	"Status" int4 NOT NULL,
	"Created" timestamptz NOT NULL,
	"CreatedBy" text NULL,
	"LastModified" timestamptz NOT NULL,
	"LastModifiedBy" text NULL,
	CONSTRAINT "PK_Works" PRIMARY KEY ("Id"),
	CONSTRAINT "FK_Works_AspNetUsers_CreatorId" FOREIGN KEY ("CreatorId") REFERENCES public."AspNetUsers"("Id") ON DELETE RESTRICT,
	CONSTRAINT "FK_Works_Plans_PlanId" FOREIGN KEY ("PlanId") REFERENCES public."Plans"("Id") ON DELETE CASCADE,
	CONSTRAINT "FK_Works_WorkTypes_WorkTypeId" FOREIGN KEY ("WorkTypeId") REFERENCES public."WorkTypes"("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_Works_CreatorId" ON public."Works" USING btree ("CreatorId");
CREATE INDEX "IX_Works_PlanId" ON public."Works" USING btree ("PlanId");
CREATE INDEX "IX_Works_WorkTypeId" ON public."Works" USING btree ("WorkTypeId");

-- public."AspNetUserClaims" definition

CREATE TABLE public."AspNetUserClaims" (
	"Id" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"UserId" text NOT NULL,
	"ClaimType" text NULL,
	"ClaimValue" text NULL,
	CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
	CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_AspNetUserClaims_UserId" ON public."AspNetUserClaims" USING btree ("UserId");

-- public."AspNetUserLogins" definition

CREATE TABLE public."AspNetUserLogins" (
	"LoginProvider" text NOT NULL,
	"ProviderKey" text NOT NULL,
	"ProviderDisplayName" text NULL,
	"UserId" text NOT NULL,
	CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
	CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_AspNetUserLogins_UserId" ON public."AspNetUserLogins" USING btree ("UserId");

-- public."AspNetUserRoles" definition

CREATE TABLE public."AspNetUserRoles" (
	"UserId" text NOT NULL,
	"RoleId" text NOT NULL,
	CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
	CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE,
	CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON public."AspNetUserRoles" USING btree ("RoleId");

-- public."AspNetUserTokens" definition

CREATE TABLE public."AspNetUserTokens" (
	"UserId" text NOT NULL,
	"LoginProvider" text NOT NULL,
	"Name" text NOT NULL,
	"Value" text NULL,
	CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
	CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE
);

-- public."Locations" definition

CREATE TABLE public."Locations" (
	"Id" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"StreetId" int4 NOT NULL,
	"HouseNumber" int4 NULL,
	"Longitude" numeric NULL,
	"Latitude" numeric NULL,
	"Description" text NULL,
	"Created" timestamptz NOT NULL,
	"CreatedBy" text NULL,
	"LastModified" timestamptz NOT NULL,
	"LastModifiedBy" text NULL,
	CONSTRAINT "PK_Locations" PRIMARY KEY ("Id"),
	CONSTRAINT "FK_Locations_Streets_StreetId" FOREIGN KEY ("StreetId") REFERENCES public."Streets"("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Locations_StreetId" ON public."Locations" USING btree ("StreetId");

-- public."TreeIncidents" definition

CREATE TABLE public."TreeIncidents" (
	"Id" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"TreeId" int4 NOT NULL,
	"ReporterId" text NOT NULL,
	"ApproverId" text NULL,
	"Content" text NULL,
	"Status" text NULL,
	"ReportedDate" timestamptz NULL,
	"Created" timestamptz NOT NULL,
	"CreatedBy" text NULL,
	"LastModified" timestamptz NOT NULL,
	"LastModifiedBy" text NULL,
	CONSTRAINT "PK_TreeIncidents" PRIMARY KEY ("Id"),
	CONSTRAINT "FK_TreeIncidents_AspNetUsers_ApproverId" FOREIGN KEY ("ApproverId") REFERENCES public."AspNetUsers"("Id") ON DELETE RESTRICT,
	CONSTRAINT "FK_TreeIncidents_AspNetUsers_ReporterId" FOREIGN KEY ("ReporterId") REFERENCES public."AspNetUsers"("Id") ON DELETE RESTRICT,
	CONSTRAINT "FK_TreeIncidents_Trees_TreeId" FOREIGN KEY ("TreeId") REFERENCES public."Trees"("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_TreeIncidents_ApproverId" ON public."TreeIncidents" USING btree ("ApproverId");
CREATE INDEX "IX_TreeIncidents_ReporterId" ON public."TreeIncidents" USING btree ("ReporterId");
CREATE INDEX "IX_TreeIncidents_TreeId" ON public."TreeIncidents" USING btree ("TreeId");

-- public."TreeLocationHistories" definition

CREATE TABLE public."TreeLocationHistories" (
	"Id" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"TreeId" int4 NOT NULL,
	"LocationId" int4 NOT NULL,
	"FromDate" timestamptz NOT NULL,
	"ToDate" timestamptz NULL,
	"Created" timestamptz NOT NULL,
	"CreatedBy" text NULL,
	"LastModified" timestamptz NOT NULL,
	"LastModifiedBy" text NULL,
	CONSTRAINT "PK_TreeLocationHistories" PRIMARY KEY ("Id"),
	CONSTRAINT "FK_TreeLocationHistories_Locations_LocationId" FOREIGN KEY ("LocationId") REFERENCES public."Locations"("Id") ON DELETE CASCADE,
	CONSTRAINT "FK_TreeLocationHistories_Trees_TreeId" FOREIGN KEY ("TreeId") REFERENCES public."Trees"("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_TreeLocationHistories_LocationId" ON public."TreeLocationHistories" USING btree ("LocationId");
CREATE INDEX "IX_TreeLocationHistories_TreeId" ON public."TreeLocationHistories" USING btree ("TreeId");

-- public."WorkDetails" definition

CREATE TABLE public."WorkDetails" (
	"Id" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"WorkId" int4 NOT NULL,
	"TreeId" int4 NOT NULL,
	"NewLocationId" int4 NULL,
	"ReplacementTreeId" int4 NULL,
	"Content" text NULL,
	"Status" text NULL,
	"Created" timestamptz NOT NULL,
	"CreatedBy" text NULL,
	"LastModified" timestamptz NOT NULL,
	"LastModifiedBy" text NULL,
	CONSTRAINT "PK_WorkDetails" PRIMARY KEY ("Id"),
	CONSTRAINT "FK_WorkDetails_Locations_NewLocationId" FOREIGN KEY ("NewLocationId") REFERENCES public."Locations"("Id") ON DELETE RESTRICT,
	CONSTRAINT "FK_WorkDetails_Trees_ReplacementTreeId" FOREIGN KEY ("ReplacementTreeId") REFERENCES public."Trees"("Id") ON DELETE RESTRICT,
	CONSTRAINT "FK_WorkDetails_Trees_TreeId" FOREIGN KEY ("TreeId") REFERENCES public."Trees"("Id") ON DELETE RESTRICT,
	CONSTRAINT "FK_WorkDetails_Works_WorkId" FOREIGN KEY ("WorkId") REFERENCES public."Works"("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_WorkDetails_NewLocationId" ON public."WorkDetails" USING btree ("NewLocationId");
CREATE INDEX "IX_WorkDetails_ReplacementTreeId" ON public."WorkDetails" USING btree ("ReplacementTreeId");
CREATE INDEX "IX_WorkDetails_TreeId" ON public."WorkDetails" USING btree ("TreeId");
CREATE INDEX "IX_WorkDetails_WorkId" ON public."WorkDetails" USING btree ("WorkId");

-- public."WorkProgresses" definition

CREATE TABLE public."WorkProgresses" (
	"Id" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"WorkId" int4 NOT NULL,
	"UpdaterId" text NOT NULL,
	"Percentage" int4 NULL,
	"Note" text NULL,
	"UpdatedDate" timestamptz NULL,
	"Created" timestamptz NOT NULL,
	"CreatedBy" text NULL,
	"LastModified" timestamptz NOT NULL,
	"LastModifiedBy" text NULL,
	CONSTRAINT "PK_WorkProgresses" PRIMARY KEY ("Id"),
	CONSTRAINT "FK_WorkProgresses_AspNetUsers_UpdaterId" FOREIGN KEY ("UpdaterId") REFERENCES public."AspNetUsers"("Id") ON DELETE RESTRICT,
	CONSTRAINT "FK_WorkProgresses_Works_WorkId" FOREIGN KEY ("WorkId") REFERENCES public."Works"("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_WorkProgresses_UpdaterId" ON public."WorkProgresses" USING btree ("UpdaterId");
CREATE INDEX "IX_WorkProgresses_WorkId" ON public."WorkProgresses" USING btree ("WorkId");

-- public."WorkUsers" definition

CREATE TABLE public."WorkUsers" (
	"Id" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"WorkId" int4 NOT NULL,
	"UserId" text NOT NULL,
	"Role" text NULL,
	"Status" text NULL,
	"Created" timestamptz NOT NULL,
	"CreatedBy" text NULL,
	"LastModified" timestamptz NOT NULL,
	"LastModifiedBy" text NULL,
	CONSTRAINT "PK_WorkUsers" PRIMARY KEY ("Id"),
	CONSTRAINT "FK_WorkUsers_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE RESTRICT,
	CONSTRAINT "FK_WorkUsers_Works_WorkId" FOREIGN KEY ("WorkId") REFERENCES public."Works"("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_WorkUsers_UserId" ON public."WorkUsers" USING btree ("UserId");
CREATE INDEX "IX_WorkUsers_WorkId" ON public."WorkUsers" USING btree ("WorkId");

-- public."TreeIncidentImages" definition

CREATE TABLE public."TreeIncidentImages" (
	"Id" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"TreeIncidentId" int4 NOT NULL,
	"Path" text NULL,
	"Description" text NULL,
	"Created" timestamptz NOT NULL,
	"CreatedBy" text NULL,
	"LastModified" timestamptz NOT NULL,
	"LastModifiedBy" text NULL,
	CONSTRAINT "PK_TreeIncidentImages" PRIMARY KEY ("Id"),
	CONSTRAINT "FK_TreeIncidentImages_TreeIncidents_TreeIncidentId" FOREIGN KEY ("TreeIncidentId") REFERENCES public."TreeIncidents"("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_TreeIncidentImages_TreeIncidentId" ON public."TreeIncidentImages" USING btree ("TreeIncidentId");
